[feat] Adding Cornerstone project
dojot/dojot-ui pull request #2
Opened 2021-11-23 18:37 UTC by cfrancisco

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR adds the microfrontend application CornerStone-GUI, used as the basis to load other MFEs in Dojot environment. 

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
This PR is related to dojot/dojot#2284

2021-11-26 13:59 UTC, LuanEdCosta requested changes
Very good job! I reviewed every file and almost all lines 😅. Hope it helps.

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/adapters/localStorage/login.localStorage.js
> +  localStorage.setItem("USER_PROFILE", profile);
I usually store all localStorage keys in a config file, example: `config/localStorage.js`. If you use these keys in other files (such as unit tests) the constant will help.

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/adapters/localStorage/theme.localStorage.test.js
> +it("save in localStorage", () => {
You can use the `describe` function to involve these two test cases

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/adapters/services/graphql.api.js
> +    // eslint-disable-next-line no-param-reassign
If possible, try not to fight Eslint 🤣

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/domain/menu/index.js
> +export * from "../../../config/visibleItems";
../../../../../WeNeedAbsoluteImports.js 😆

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/presentation/components/Containers/Containers.test.js
> +import "@testing-library/jest-dom/extend-expect";
I think this kind of config usually is placed in a `setupTests.js` file 🤔

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/presentation/components/Containers/ViewContainer.jsx
> +// import { connect } from "react-redux";
You may be able to remove these comments or add a message explaining why they should remain commented.

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/presentation/components/Containers/containers.style.js
> +    marginTop: 64,
This is 64px?
If `theme.spacing(1) === 16px`, `theme.spacing(4) === 64px`

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/presentation/components/Header/AppHeader.jsx
> +import MenuIcon from "@material-ui/icons/Menu";
Whats the difference between `@material-ui/icons` and `@mui/icons-material`?

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/presentation/utils/hooks/useLocalStorage.js
> +// Hook
Maybe you can use JsDoc to document the hook and remove some comments. 

Uncle Bob says in the Clean Code Book:

> Comments are a last resort
> The proper use of comments is: to compensate for our failure to express ourselves in code. Every use of a comment represents a failure. So don't comment first. Try everything else, then comment as a last resort.

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/presentation/utils/i18n.js
> +    escapeValue: false,
Security vulnerability?

[i18next Docs - Interpolation](https://www.i18next.com/translation-function/interpolation)

![image](https://user-images.githubusercontent.com/36794274/143589150-a0923730-6614-4824-9cf4-c15e580cf6b9.png)

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/src/presentation/views/notFound/notFound.jsx
> +      <b>Not Found</b>
Is it possible to use i18next here?

2021-11-26 13:59 UTC, LuanEdCosta commented on cornerstone/package.json
> +    "react": "^17.0.2",
With React 17.x.x you don't need to `import React from 'react'` in every JSX file thanks to the new JSX transformation. To be able to remove these imports some extra babel configs will probably be necessary: [React Docs](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)

2021-11-29 16:34 UTC, cfrancisco commented on cornerstone/builder/index.js
> +  if (menuItens !== undefined) {
Thanks for remembering me. In fact, for this code, I only want to check it undefined (the ENV variable wasn't passed). Nevertheless, I will change it to make it more clear.

2021-11-29 16:41 UTC, cfrancisco commented on cornerstone/builder/index.js
> +    if (cnfg === undefined) {
I know... but if the only option is undefined (I mean, there's no way to get null in this code), should also compare with null or not?

2021-11-29 16:57 UTC, cfrancisco commented on cornerstone/package.json
> +    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
Thanks!! The 'babel/* dependencies" have passed unnoticed by me.

2021-11-29 17:08 UTC, cfrancisco commented on cornerstone/package.json
> +  "jest": {
Thanks! Although the configuration was nearly identical, I updated it following your example.
bout the file, it is my intention to avoid extra files whenever possible.

2021-11-29 17:38 UTC, cfrancisco commented on cornerstone/public/index.html
> +<html>
Thanks! I also added some other missing metatags.

2021-11-29 17:45 UTC, cfrancisco commented on cornerstone/.eslintrc
> +  "extends": [
I'm already doing that in "extends: ["prettier"]". This integration requires only that much, as mentioned in https://github.com/prettier/eslint-config-prettier

2021-11-29 19:27 UTC, cfrancisco commented on cornerstone/src/App.js
> +import { getThemeSchema, THEME_TYPES } from "./presentation/themes";
Great tip! After researching, I fixed the import issues by adding a new plugin.

2021-11-29 19:54 UTC, cfrancisco commented on cornerstone/src/adapters/localStorage/login.localStorage.js
> +  localStorage.setItem("USER_PROFILE", profile);
I totally agree with you. This code is temporary, but when updating to keycloack configuration, we should use constants.

2021-11-29 19:57 UTC, cfrancisco commented on cornerstone/src/adapters/localStorage/theme.localStorage.test.js
> +it("save in localStorage", () => {
Nice! I hadn't noticed that.

2021-11-29 19:58 UTC, cfrancisco commented on cornerstone/src/domain/menu/index.js
> +export * from "../../../config/visibleItems";
IHopeNot haskhas

2021-11-29 20:01 UTC, cfrancisco commented on cornerstone/src/adapters/services/graphql.api.js
> +    // eslint-disable-next-line no-param-reassign
Yep! This code should be removed soon (I didn't even work in this login spaghetti code).

2021-11-29 20:16 UTC, cfrancisco commented on cornerstone/src/presentation/components/Containers/Containers.test.js
> +import "@testing-library/jest-dom/extend-expect";
That's true! The file was added and all imports were updated.

2021-11-29 20:19 UTC, cfrancisco commented on cornerstone/src/presentation/components/Containers/containers.style.js
> +    marginTop: 64,
Initially, I almost changed it, but 64px in this scenario is not related to spacing, so, for me, it shouldn't be bonded.

2021-11-29 20:21 UTC, cfrancisco commented on cornerstone/src/presentation/components/Containers/ViewContainer.jsx
> +// import { connect } from "react-redux";
You are right. I will remove these lines.

2021-11-29 20:37 UTC, cfrancisco commented on cornerstone/src/presentation/components/Header/AppHeader.jsx
> +import MenuIcon from "@material-ui/icons/Menu";
@mui/icons-material uses Material UI v5, I'll change all icons to the newer one.

2021-11-29 20:38 UTC, cfrancisco commented on cornerstone/package.json
> +    "react": "^17.0.2",
Yep! In a second review, I noticed that, updated!! :)

2021-11-29 20:44 UTC, cfrancisco commented on cornerstone/src/presentation/views/notFound/notFound.jsx
> +      <b>Not Found</b>
Sure. In fact, we need to create this page following the UX specification.

2021-11-29 20:48 UTC, cfrancisco commented on cornerstone/src/presentation/utils/hooks/useLocalStorage.js
> +// Hook
Kkkkk. I really like the Uncle Bob and the Clean Code 'normatives'. 

But about the code, since we aren't using it, this should be removed.

2021-11-29 20:54 UTC, cfrancisco commented on cornerstone/src/presentation/utils/i18n.js
> +    escapeValue: false,
Hm... Thanks!! It came from GUI-NX code. I just updated removing the escapeValue, but maybe we should check in GUI-NX as well.

2021-11-30 17:28 UTC, LuanEdCosta commented on cornerstone/.eslintrc
> +  "extends": [
Ok :+1:

2021-11-30 17:29 UTC, LuanEdCosta commented on cornerstone/builder/index.js
> +  if (menuItens !== undefined) {
Ok :+1:

2021-11-30 17:29 UTC, LuanEdCosta commented on cornerstone/package.json
> +  "jest": {
Ok :+1:

2021-11-30 17:30 UTC, LuanEdCosta commented on cornerstone/src/presentation/components/Header/AppHeader.jsx
> +import MenuIcon from "@material-ui/icons/Menu";
Nice, MUI v5 brings a lot of improvements!

2021-11-30 17:33 UTC, LuanEdCosta commented on cornerstone/src/presentation/utils/i18n.js
> +    escapeValue: false,
:fearful::fearful::fearful:

2021-11-30 17:33 UTC, LuanEdCosta commented on cornerstone/package.json
> +    "react": "^17.0.2",
Nice!

2021-11-30 17:35 UTC, LuanEdCosta commented on cornerstone/builder/index.js
> +    if (cnfg === undefined) {
If the only option is undefined you don't need to compare if it is null, but just using `if(variable)` is more elegant and is useful for all falsy values.

2021-11-30 17:36 UTC, LuanEdCosta commented on cornerstone/src/App.js
> +import { getThemeSchema, THEME_TYPES } from "./presentation/themes";
Nice

2021-11-30 17:38 UTC, LuanEdCosta commented on cornerstone/src/adapters/services/graphql.api.js
> +    // eslint-disable-next-line no-param-reassign
I forgot that some pieces of code came from GUI NX. We will fix all these problems in the future

2021-12-03 15:48 UTC, cfrancisco commented on cornerstone/public/index.html
> +    <meta content="width=device-width" name="viewport" />
I'll update it in the next revision!

2021-12-03 15:48 UTC, merged